filters:
  - label: ğŸ Fix
    regexs:
      - /^.{0,10}\bfix\b/i
    events: [issues, pull_request]
    targets: [title]

  - label: ğŸ“„ Docs
    regexs:
      - /^.{0,10}\bdocs\b/i
    events: [issues, pull_request]
    targets: [title]

  - label: ğŸ¨ Style
    regexs:
      - /^.{0,10}\bstyle\b/i
    events: [issues, pull_request]
    targets: [title]

  - label: ğŸ”¨ Refactor
    regexs:
      - /^.{0,10}\brefactor\b/i
    events: [issues, pull_request]
    targets: [title]

  - label: ğŸ“¬ API
    regexs:
      - /^.{0,10}\bapi\b/i
    events: [issues, pull_request]
    targets: [title]

  - label: âœ… Test
    regexs:
      - /^.{0,10}\btest\b/i
    events: [issues, pull_request]
    targets: [title]
